### ISSUE TITLE
monitor_closest_beacon = true: Crash on iPhone 4S

### ISSUE THREAD

**Issue by alvincrisuy** [RadiusNetworks/proximitykit-ios#6]
The issue persist only in iPhone 4S when the monitor_closest_beacon is set to true.

Other devices works fine.

-[__NSCFType integerValue]: unrecognized selector sent to instance 0x14d786f0

**Comment by alvincrisuy** [comment]
Added Issue: -[NSConcreteValue integerValue]: unrecognized selector sent to instance 0x17e87870

**Comment by greencoder** [comment]
I tried this on a 4S and I wasn't able to replicate the crash. Would it be possible to send information from a stack trace so I can narrow it down?

Also, if you can send the configuration dictionary or plist, that might help. Feel free to email it to me (snewman AT radiusnetworks.com) instead of posting it publicly here.

**Comment by alvincrisuy** [comment]
Thank you! I send an email 👍

**Comment by gabriele-cossu** [comment]
Hi,
I have the same problem (maybe?) with an iPhone 5/c.
The exception is :
`[_UIImageAssetMapEnvelope integerValue]: unrecognized selector sent to instance 0x17debd10`

How can I solve this?
Thanks in advance,

Gabriele

**Comment by alvincrisuy** [comment]
@gabriele-cossu this is too late for my reply. I hope this will also help others.

On what I experience is, it is only happening when i'm debugging. Not on the production. I don't know either what is the cause of this issue when in debug mode. Thanks
